# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0
      uses: actions/setup-java@v1
      with:
        java-version: 11.0
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Archive results 1
      uses: actions/upload-artifact@v1
      with:
        name: WorldJam shaded jar
        path: target/WorldJam-0.0.1-SNAPSHOT-shaded.jar
    - name: Archive results 2
      uses: actions/upload-artifact@v1
      with:
        name: WorldJam exe for Windows
        path: target/WorldJam.exe
    - name: Archive results 3
      uses: actions/upload-artifact@v1
      with:
        name: WorldJam dmg for Mac
        path: target/WorldJam_0.0.1-SNAPSHOT.dmg
      
